### ISSUE TITLE
notes lag very bad

### ISSUE THREAD

**Issue by g4269159** [kbz/SIFTrain#1]
It happened after the 1.2.2  update, this is how it looks like
https://youtu.be/DmK1elH5HkM
I'm using Samsung SM-T235 with Android 4.4.2

**Comment by kbz** [comment]
Hi, guess that was introduced with the sync patch, I'll try to see what I can do to fix it. Thanks for your report.

**Comment by kbz** [comment]
Hopefully in 1.2.3 this issue is resolved, please tell me after you've updated. The update should be available in a couple of hours.

**Comment by g4269159** [comment]
It works now, thank you very much.
Do you think it would it be possible to number the screen like this? It would be very helpful for people that are switching from a phone/tablet to BlueStacks and want to train playing with a keyboard. Thank you very much for making this app, it's incredibly useful.
![rlfatjr](https://cloud.githubusercontent.com/assets/12631492/8399810/5c29cf86-1e15-11e5-9e44-ac3e8412571f.png)
