### ISSUE TITLE
Notes out of sync

### ISSUE THREAD

**Issue by ghost** [kbz/SIFTrain#3]
Since the latest update I have noticed that you most likely changed the function of the offset slider to affect the start point of the notes / song rather than affecting the hit timing for notes. the issue with doing that is that people (such as myself) who are used to an offset on SIF now are stuck with essentially a 0 offset, since with the new setting the notes might sound in sync with the song but hitting the notes is now unchanged from default.

If you could add the old function as a separate option that would be appreciated

**Comment by kbz** [comment]
Ok, so a second offset setting to compensate for input lag, right? I'll get to it tomorrow. Thanks for your input.

**Comment by kbz** [comment]
I've added this change and should be up in a couple of hours, please check if it works.

**Comment by ghost** [comment]
Yep the offset works perfectly, nicely done.
